export const ADDCANCELREQUEST = 'ADDCANCELREQUEST';
export const CLEARCANCELREQUEST = 'CLEARCANCELREQUEST';
export const QUERYALLSERVICE = 'QUERYALLSERVICE';
export const SETSELECTSERVICE = 'SETSELECTSERVICE';